# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemSize', models.CharField(max_length=50)),
                ('stockRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saleRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('itemAvailable', models.IntegerField(default=0)),
                ('itemFree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenMemoNo', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='SaleMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Customer')),
                ('saleItem', models.ManyToManyField(to='WebApp.SaleItem')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=20)),
                ('salesRepresentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.SalesRepresentative')),
            ],
        ),
        migrations.AddField(
            model_name='purchasememo',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Supplier'),
        ),
        migrations.AddField(
            model_name='purchasememo',
            name='purchaseItem',
            field=models.ManyToManyField(to='WebApp.PurchaseItem'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesRepresentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.SalesRepresentative'),
        ),
    ]
