# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_no',
            new_name='mobileNo',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='mobile_no',
            new_name='mobileNo',
        ),
    ]
