# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20180129_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='purchaseRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='saleRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
