# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20180210_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
