# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_saleitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
