# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_purchaseitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='mobileNo',
            field=models.CharField(default=1000099999, max_length=20),
            preserve_default=False,
        ),
    ]
