# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20180211_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasememo',
            name='actualTotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salememo',
            name='actualTotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
