# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20180211_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasememo',
            name='givenMemoNo',
            field=models.CharField(max_length=50),
        ),
    ]
