# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20180309_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('free', models.IntegerField(default=0)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnSaleMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenMemoNo', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('memoTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('actualTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Customer')),
                ('saleItem', models.ManyToManyField(to='WebApp.SaleItem')),
            ],
        ),
    ]
