# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_returnsaleitem_returnsalememo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnsaleitem',
            name='item',
        ),
        migrations.RenameField(
            model_name='returnsalememo',
            old_name='saleItem',
            new_name='returnSaleItem',
        ),
        migrations.RemoveField(
            model_name='returnsalememo',
            name='party',
        ),
        migrations.AlterField(
            model_name='returnsalememo',
            name='givenMemoNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.SaleMemo'),
        ),
        migrations.DeleteModel(
            name='ReturnSaleItem',
        ),
    ]
